
--LAB 3

--BAI TAP BAT BUOC
SET DATEFORMAT DMY
USE QLBH

--III. 30

SELECT MASP, TENSP FROM SANPHAM
WHERE NUOCSX='Trung Quoc' AND GIA IN (
		SELECT DISTINCT TOP 3 GIA 
		FROM SANPHAM
		WHERE NUOCSX='Trung Quoc'
		ORDER BY GIA DESC
)

--III. 31

SELECT TOP 3 *, RANK() OVER (ORDER BY DOANHSO DESC) AS DS_RANK FROM KHACHHANG
 
--III. 32

SELECT COUNT(MASP) AS SO_SP FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'

--III. 33

SELECT NUOCSX, COUNT(MASP) AS SO_SP FROM SANPHAM
GROUP BY NUOCSX

--III. 34

SELECT NUOCSX, MAX(GIA) AS MAX_GIA, MIN(GIA) AS MIN_GIA, AVG(GIA) AS AVG_GIA FROM SANPHAM
GROUP BY NUOCSX

--III. 35

SELECT NGHD, SUM(TRIGIA) AS DOANHTHU FROM HOADON
GROUP BY NGHD

--III. 36

SELECT MASP, SUM(SL) AS SL
FROM HOADON INNER JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE MONTH(NGHD)=10 AND YEAR(NGHD)=2006
GROUP BY MASP

--III. 37

SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU FROM HOADON
WHERE YEAR(NGHD)=2006
GROUP BY MONTH(NGHD)

--III. 38

SELECT * FROM HOADON
WHERE SOHD IN (
	SELECT SOHD
	FROM CTHD
	GROUP BY SOHD
	HAVING COUNT(MASP) >= 4
)

--III. 39
SELECT * FROM HOADON
WHERE SOHD IN (
	SELECT SOHD
	FROM CTHD INNER JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
	WHERE NUOCSX = 'Viet Nam'
	GROUP BY SOHD
	HAVING COUNT(CTHD.MASP) >= 3
)

--III. 40

SELECT MAKH, HOTEN FROM KHACHHANG
WHERE MAKH IN (
	SELECT MAKH
	FROM HOADON
	GROUP BY MAKH
	HAVING COUNT(SOHD)>=(
		SELECT MAX(SL_HD) AS SL
		FROM( 
			SELECT MAKH, COUNT(SOHD) AS SL_HD
			FROM HOADON
			WHERE MAKH IS NOT NULL
			GROUP BY MAKH) AS T
	)
)

---III. 41

SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHSO
FROM HOADON
GROUP BY MONTH(NGHD)
HAVING SUM(TRIGIA) = (
	SELECT MAX(DOANHSO) FROM (
		SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHSO
		FROM HOADON
		WHERE YEAR(NGHD)=2006
		GROUP BY MONTH(NGHD)
	) AS T
)

--III. 42

SELECT SANPHAM.MASP, TENSP 
FROM SANPHAM INNER JOIN CTHD ON SANPHAM.MASP=CTHD.MASP
WHERE SOHD IN (
	SELECT SOHD FROM CTHD
	GROUP BY SOHD 
	HAVING SUM(SL) = (
		SELECT MIN(TONGSL) AS MIN_TONGSL  FROM(
			SELECT SOHD, SUM(SL) AS TONGSL FROM CTHD
			GROUP BY SOHD
		) AS T
	)
)

--III. 43

SELECT NUOCSX, MASP, TENSP FROM SANPHAM AS SP1
WHERE GIA >= (
	SELECT MAX(GIA) FROM SANPHAM AS SP2
	WHERE SP1.NUOCSX = SP2.NUOCSX
)

--III. 44

SELECT NUOCSX, COUNT(DISTINCT GIA) AS SLGIA
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3

--III. 45

SELECT * FROM KHACHHANG
WHERE MAKH = (
	SELECT TOP 1 T1.MAKH FROM (
		SELECT TOP 10 MAKH FROM KHACHHANG
		ORDER BY DOANHSO DESC) AS T1 
	INNER JOIN (
		SELECT MAKH, COUNT(SOHD) AS SL FROM HOADON
		GROUP BY MAKH) AS T2 
	ON T1.MAKH = T2.MAKH
)

---BAI TAP LAM THEM
USE QLGV

--III. 17

SELECT HOCVIEN.*, DIEM FROM HOCVIEN, KETQUATHI
WHERE
	HOCVIEN.MAHV = KETQUATHI.MAHV
	AND MAMH = 'CSDL'
	AND LANTHI = (
		SELECT MAX(LANTHI) 
		FROM KETQUATHI 
		WHERE MAMH = 'CSDL' AND KETQUATHI.MAHV = HOCVIEN.MAHV 
		GROUP BY MAHV
	)

--III. 18

SELECT HOCVIEN.*, DIEM FROM HOCVIEN, KETQUATHI
WHERE
	HOCVIEN.MAHV = KETQUATHI.MAHV
	AND MAMH = 'CSDL'
	AND DIEM = (
		SELECT MAX(DIEM) 
		FROM KETQUATHI 
		WHERE MAMH = 'CSDL' AND KETQUATHI.MAHV = HOCVIEN.MAHV 
		GROUP BY MAHV
	)

--III.19

SELECT MAKHOA, TENKHOA FROM KHOA
WHERE NGTLAP = (
	SELECT MIN(NGTLAP) FROM KHOA
)

--III. 20

SELECT COUNT(MAGV) AS SL_GS_PGS 
FROM GIAOVIEN
WHERE HOCHAM IN ('GS', 'PGS')

--III.21

SELECT MAKHOA AS KHOA, HOCVI, COUNT(MAGV) AS SL_GV 
FROM GIAOVIEN
GROUP BY MAKHOA, HOCVI
ORDER BY MAKHOA

--III. 22

SELECT MAMH, KQUA, COUNT(DISTINCT MAHV) AS SL_HV 
FROM KETQUATHI
GROUP BY MAMH, KQUA
ORDER BY MAMH

--III.23

SELECT DISTINCT GIAOVIEN.MAGV, HOTEN 
FROM GIAOVIEN INNER JOIN LOP ON GIAOVIEN.MAGV = LOP.MAGVCN
	INNER JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
WHERE LOP.MAGVCN = GIANGDAY.MAGV

--III.24

SELECT CONCAT(HO,' ',TEN) AS HOTEN
FROM HOCVIEN INNER JOIN LOP ON HOCVIEN.MAHV = LOP.TRGLOP
WHERE SISO = (SELECT DISTINCT MAX(SISO) FROM LOP)

--III. 25

SELECT CONCAT(HO,' ',TEN) AS HOTEN
FROM HOCVIEN INNER JOIN LOP ON HOCVIEN.MAHV = LOP.TRGLOP
	INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE  KQUA = 'Khong Dat'
GROUP BY TRGLOP,  CONCAT(HO,' ',TEN)
HAVING COUNT(*) > 3

--III. 26

SELECT HOCVIEN.MAHV, CONCAT(HO,' ',TEN) AS HOTEN
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE DIEM >= 9
GROUP BY HOCVIEN.MAHV, HO, TEN
HAVING COUNT(*) >= ALL(
	SELECT COUNT(*) FROM KETQUATHI 
	WHERE DIEM >= 9 
	GROUP BY MAHV
) 

--III.27

SELECT MALOP, MAHV, HOTEN
FROM (
	SELECT MALOP, HOCVIEN.MAHV, CONCAT(HO,' ',TEN) AS HOTEN, COUNT(*) AS SLDIEM, 
		RANK() OVER (PARTITION BY MALOP ORDER BY COUNT(*) DESC) AS XEPHANG
	FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
	WHERE DIEM >= 9 
	GROUP BY MALOP, HOCVIEN.MAHV, HO, TEN
) AS T
WHERE T.XEPHANG = 1

--III.28

SELECT MAGV, COUNT(DISTINCT MAMH) AS SL_MONHOC, COUNT(DISTINCT MALOP) AS SL_LOP
FROM GIANGDAY
GROUP BY MAGV

--III.29

SELECT HOCKY, NAM, T.MAGV, HOTEN
FROM GIAOVIEN INNER JOIN (
	SELECT HOCKY, NAM, MAGV, 
		RANK() OVER (PARTITION BY HOCKY, NAM ORDER BY COUNT(*) DESC) AS XEPHANG
	FROM GIANGDAY
	GROUP BY HOCKY, NAM, MAGV
) AS T ON GIAOVIEN.MAGV = T.MAGV
WHERE XEPHANG = 1
ORDER BY NAM, HOCKY
	

--III.30
SELECT MONHOC.MAMH, TENMH
FROM MONHOC INNER JOIN KETQUATHI ON MONHOC.MAMH = KETQUATHI.MAMH
WHERE LANTHI = 1 AND KQUA = 'KHONG DAT'
GROUP BY MONHOC.MAMH, TENMH
HAVING COUNT(*) >= ALL (
	SELECT COUNT(*) FROM KETQUATHI 
	WHERE LANTHI = 1 AND KQUA = 'KHONG DAT' 
	GROUP BY MAMH
)
	

--III.31
SELECT DISTINCT HOCVIEN.MAHV, CONCAT(HO,' ',TEN) AS HOTEN
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE NOT EXISTS (
	SELECT * FROM KETQUATHI
	WHERE LANTHI = 1 AND KQUA = 'KHONG DAT' AND MAHV = HOCVIEN.MAHV
)
	
--III.32
SELECT DISTINCT HOCVIEN.MAHV, CONCAT(HO,' ',TEN) AS HOTEN
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE NOT EXISTS (
	SELECT * FROM KETQUATHI
	WHERE KQUA = 'KHONG DAT' AND MAHV = HOCVIEN.MAHV
		AND LANTHI = (
			SELECT MAX(LANTHI) FROM KETQUATHI 
			WHERE MAHV = HOCVIEN.MAHV 
			GROUP BY MAHV
		)
)
