USE QLBH

--LAB 2

--III.1

SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'

--III.2

SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN ('cay', 'quyen')

--III.3

SELECT MASP, TENSP
FROM SANPHAM
WHERE SUBSTRING(MASP,1,1) = 'B' AND SUBSTRING(MASP,3,2) = '01'

--III.4

SELECT MASP, TENSP
FROM SANPHAM
WHERE (GIA BETWEEN 30000 AND 40000) AND NUOCSX = 'Trung Quoc'

--III.5

SELECT MASP, TENSP
FROM SANPHAM
WHERE (GIA >= 30000 AND GIA <= 40000) AND (NUOCSX IN ('Trung Quoc', 'Thai Lan'))

--III.6

SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD='1/1/2007' AND NGHD='2/1/2007'

--III.7

SELECT SOHD, TRIGIA
FROM HOADON
WHERE MONTH(NGHD)=1 AND YEAR(NGHD)=2007
ORDER BY NGHD ASC, TRIGIA DESC 

--III.8

SELECT KHACHHANG.MAKH, HOTEN
FROM KHACHHANG INNER JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE NGHD = '01/01/2007'

--III.9

SET DATEFORMAT DMY 
SELECT SOHD, TRIGIA
FROM HOADON INNER JOIN NHANVIEN ON HOADON.MANV = NHANVIEN.MANV
WHERE NGHD = '28/10/2006' AND HOTEN = 'Nguyen Van B'

--III.10

SELECT SANPHAM.MASP, TENSP
FROM CTHD INNER JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
          INNER JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
		  INNER JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE HOTEN = 'NGuyen Van A' AND YEAR(NGHD)=2006 AND MONTH(NGHD)=10

--III.11

SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP='BB01' OR MASP='BB02'

--III.12

SELECT SOHD 
FROM CTHD 
WHERE MASP = 'BB01' AND SL >= 10 AND SL <= 20
UNION
SELECT SOHD
FROM CTHD 
WHERE MASP = 'BB02' AND SL >= 10 AND SL <= 20

--III.13

SELECT SOHD 
FROM CTHD 
WHERE MASP = 'BB01' AND SL >= 10 AND SL <= 20
INTERSECT
SELECT SOHD 
FROM CTHD 
WHERE MASP = 'BB02' AND SL >= 10 AND SL <= 20

--III.14

SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX='Trung Quoc' 
UNION
SELECT SANPHAM.MASP, TENSP
FROM SANPHAM INNER JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
             INNER JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
WHERE NGHD='1/1/2007'

--III.15

--CACH 1
SELECT MASP, TENSP
FROM SANPHAM
EXCEPT
SELECT SANPHAM.MASP, TENSP
FROM SANPHAM INNER JOIN CTHD ON CTHD.MASP = SANPHAM.MASP

--CACH 2
USE QLBH
SELECT SANPHAM.MASP,TENSP
FROM SANPHAM LEFT OUTER JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
WHERE SOHD IS NULL

--Bai tap lam them

USE QLGV

--III.1

SELECT DISTINCT HOCVIEN.MAHV, CONCAT(HO, ' ', TEN) AS HOTEN, NGSINH, HOCVIEN.MALOP
FROM LOP INNER JOIN HOCVIEN ON HOCVIEN.MAHV = LOP.TRGLOP

--III.2

SELECT HOCVIEN.MAHV, CONCAT(HO, ' ', TEN) AS HOTEN, LANTHI, DIEM
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV=KETQUATHI.MAHV
WHERE MALOP='K12' AND MAMH='CTRR'
ORDER BY TEN ASC, HO ASC

--III.3

SELECT DISTINCT HOCVIEN.MAHV, CONCAT(HO, ' ', TEN) AS HOTEN, MAMH
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV=KETQUATHI.MAHV
WHERE LANTHI=1 AND KQUA='Dat'

--III.4

SELECT DISTINCT HOCVIEN.MAHV, CONCAT(HO, ' ', TEN) AS HOTEN
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV=KETQUATHI.MAHV
WHERE MALOP='K11' AND MAMH='CTRR' AND KQUA='Khong Dat'

--III.5

SELECT DISTINCT HOCVIEN.MAHV, CONCAT(HO, ' ', TEN) AS HOTEN
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV=KETQUATHI.MAHV
WHERE SUBSTRING(MALOP,1,1)='K' AND MAMH='CTRR' AND KQUA='Khong Dat'


--III.6

SELECT DISTINCT TENMH
FROM MONHOC INNER JOIN GIANGDAY ON MONHOC.MAMH=GIANGDAY.MAMH
INNER JOIN GIAOVIEN ON GIANGDAY.MAGV=GIAOVIEN.MAGV
WHERE HOTEN = 'Tran Tam Thanh' AND HOCKY = 1 AND NAM = 2006
