
--BAI TAP BAT BUOC

USE QLBH
SET DATEFORMAT DMY

--I.10

CREATE TRIGGER TRG_NGDK_NGSINH ON KHACHHANG
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGDK SMALLDATETIME, @NGSINH SMALLDATETIME
	SELECT @NGDK = NGDK, @NGSINH = NGSINH FROM inserted
	IF (@NGDK < @NGSINH)
		BEGIN
			PRINT 'LOI, NGAY DANG KY PHAI SAU NGAY SINH'
			ROLLBACK TRANSACTION
		END
END

--I.11

CREATE TRIGGER TRG_HOADON ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NG_MUAHANG SMALLDATETIME, @NG_DK SMALLDATETIME, @MAKH CHAR(4)
	SELECT @NG_MUAHANG = NGHD, @MAKH = MAKH FROM inserted
	SELECT @NG_DK = NGDK FROM KHACHHANG WHERE MAKH = @MAKH
	IF (@NG_MUAHANG < @NG_DK)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT 'LOI, NGAY MUA HANG PHAI SAU NGAY DANG KY'
		END
END

CREATE TRIGGER TRG_KHACHHANG ON KHACHHANG
FOR UPDATE
AS
BEGIN
	DECLARE @NG_MUAHANG SMALLDATETIME, @NG_DK_DANGSUA SMALLDATETIME, @MAKH CHAR(4)
	SELECT @MAKH = MAKH, @NG_DK_DANGSUA = NGDK FROM inserted
	SELECT @NG_MUAHANG = MIN(NGHD) FROM HOADON WHERE MAKH = @MAKH
	IF (@NG_MUAHANG < @NG_DK_DANGSUA)
		BEGIN
			PRINT 'LOI, NGAY MUA HANG PHAI SAU NGAY DANG KY'
			ROLLBACK TRANSACTION
		END
END

--I.12

CREATE TRIGGER TRG_NGVL_NGHD ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGHD SMALLDATETIME, @NGVL SMALLDATETIME, @MANV CHAR(4)
	SELECT @NGHD = NGHD, @MANV = MANV FROM inserted
	SELECT @NGVL = NGVL FROM NHANVIEN WHERE MANV = @MANV
	IF (@NGHD < @NGVL)
		BEGIN
			PRINT 'LOI, NGAY HOA DON PHAI SAU NGAY NHAN VIEN VAO LAM'
			ROLLBACK TRANSACTION
		END
END

CREATE TRIGGER TRG_NV_NGVL_NGHD ON NHANVIEN
FOR UPDATE
AS
BEGIN
	DECLARE @NGHD SMALLDATETIME, @NGVL SMALLDATETIME, @MANV CHAR(4)
	SELECT @NGVL = NGVL, @MANV = MANV FROM inserted
	SELECT @NGHD = MIN(NGHD) FROM HOADON WHERE MANV = @MANV
	IF (@NGHD < @NGVL)
		BEGIN
			PRINT 'LOI, NGAY HOA DON PHAI SAU NGAY NHAN VIEN VAO LAM'
			ROLLBACK TRANSACTION
		END
END

--I.13

CREATE TRIGGER TRG_UPDATE_CTHD ON CTHD
FOR UPDATE
AS
BEGIN
	DECLARE @SOHD_CT INT, @SOHD_HD INT
	SELECT @SOHD_CT = SOHD FROM inserted
	SELECT @SOHD_HD = SOHD FROM HOADON WHERE SOHD = @SOHD_CT
	IF (@SOHD_CT != @SOHD_HD)
		BEGIN
			PRINT 'LOI'
			ROLLBACK TRANSACTION
		END
END

CREATE TRIGGER TRG_DEL_CTHD ON CTHD
FOR DELETE
AS
BEGIN
	DECLARE @SOHD_CT INT, @SOHD_HD INT
	SELECT @SOHD_CT = SOHD FROM deleted
	SELECT @SOHD_HD = SOHD FROM HOADON WHERE SOHD = @SOHD_CT
	IF ((SELECT COUNT(SOHD) FROM CTHD WHERE SOHD = @SOHD_HD) < 1)
		BEGIN
			PRINT 'LOI, KHONG THE XOA'
			ROLLBACK TRANSACTION
		END
END

--I.14

CREATE TRIGGER TRG_UPDATE_HOADON_TRIGIA ON HOADON
FOR UPDATE
AS
BEGIN
	DECLARE @SOHD_UPDATE INT, @TRIGIA_UPDATE MONEY, @TRIGIA_NON_UPDATE MONEY
	SELECT @SOHD_UPDATE = SOHD, @TRIGIA_UPDATE = TRIGIA FROM inserted
	SELECT @TRIGIA_NON_UPDATE = TRIGIA FROM HOADON WHERE SOHD = @SOHD_UPDATE
	IF (@TRIGIA_UPDATE != @TRIGIA_NON_UPDATE)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT 'KHONG THE SUA TRUC TIEP TRI GIA HOA DON'
		END
END

CREATE TRIGGER TRG_INSERT_CTHD_TRIGIA ON CTHD
FOR INSERT
AS
BEGIN
	DECLARE @SOHD_CT INT, @MASP_CT CHAR(4), @SL INT, @MASP_SP CHAR(4), @GIA MONEY
	SELECT @SOHD_CT = SOHD, @MASP_CT = MASP, @SL = SL FROM inserted
	SELECT @MASP_SP = MASP, @GIA = GIA FROM SANPHAM  WHERE MASP = @MASP_CT
	
	UPDATE HOADON
	SET TRIGIA = TRIGIA + @SL * @GIA
	WHERE SOHD = @SOHD_CT

	PRINT 'THEM THANH CONG CTHD VA UPDATE TRIGIA CUA HOA DON TUONG UNG'
END

CREATE TRIGGER TRG_UPDATE_CTHD_TRIGIA ON CTHD
FOR UPDATE
AS
BEGIN
	DECLARE @SOHD_CU INT, @SOHD_MOI INT, @MASP_CU CHAR(4), @MASP_MOI CHAR(4), @SL_CU INT, @SL_MOI INT, @GIA_CU MONEY, @GIA_MOI MONEY

	SELECT @SOHD_CU = SOHD, @MASP_CU = MASP, @SL_CU = SL FROM  deleted
	SELECT @SOHD_MOI = SOHD, @MASP_MOI = MASP, @SL_MOI = SL FROM  inserted
	SELECT @GIA_CU = GIA FROM SANPHAM WHERE MASP = @MASP_CU
	SELECT @GIA_MOI = GIA FROM SANPHAM WHERE MASP = @MASP_MOI
	
	IF(@SOHD_CU = @SOHD_MOI)
		BEGIN
			UPDATE HOADON
			SET TRIGIA = TRIGIA + @SL_MOI * @GIA_MOI - @SL_CU * @GIA_CU
			WHERE SOHD = @SOHD_CU
		END
	ELSE
		BEGIN
			UPDATE HOADON
			SET TRIGIA = TRIGIA - @SL_CU * @GIA_CU
			WHERE SOHD = @SOHD_CU
			UPDATE HOADON
			SET TRIGIA = TRIGIA + @SL_MOI * @GIA_MOI
			WHERE SOHD = @SOHD_MOI
		END
	PRINT'CAP NHAT THANH CONG CTHD VA UPDATE LAI TRIGIA HOA DON TUONG UNG'
END

CREATE TRIGGER TRG_DELETE_CTHD_TRIGIA ON CTHD
FOR DELETE
AS
BEGIN
	DECLARE @SOHD_CT INT, @MASP_CT CHAR(4), @SL INT, @MASP_SP CHAR(4), @GIA MONEY
	SELECT @SOHD_CT = SOHD, @MASP_CT = MASP, @SL = SL FROM deleted
	SELECT @MASP_SP = MASP, @GIA = GIA FROM SANPHAM  WHERE MASP = @MASP_CT

	UPDATE HOADON
	SET TRIGIA = TRIGIA - @SL * @GIA
	WHERE SOHD = @SOHD_CT

	PRINT 'XOA THANH CONG CTHD VA UPDATE LAI TRI GIA CUA HOADON TUONG UNG'
END

--I.15

CREATE TRIGGER TRG_UPDATE_KHACHHANG_DOANHSO ON KHACHHANG
FOR UPDATE
AS
BEGIN
	DECLARE @MAKH_UPDATE CHAR(4), @DOANHSO_UPDATE MONEY, @DOANHSO_NON_UPDATE MONEY
	SELECT @DOANHSO_UPDATE = DOANHSO, @DOANHSO_UPDATE = DOANHSO FROM inserted
	SELECT @DOANHSO_NON_UPDATE = DOANHSO FROM KHACHHANG WHERE MAKH = @MAKH_UPDATE
	IF (@DOANHSO_UPDATE != @DOANHSO_NON_UPDATE)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT 'KHONG THE SUA TRUC TIEP DOANH SO KHACHHANG'
		END
END

CREATE TRIGGER TRG_INSERT_HOADON_DOANHSO ON HOADON
FOR INSERT
AS
BEGIN
	DECLARE @MAKH INT, @TRIGIA MONEY
	SELECT @MAKH = MAKH, @TRIGIA = TRIGIA FROM inserted

	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO + @TRIGIA
	WHERE MAKH = @MAKH

	PRINT 'THEM THANH CONG HOADON VA UPDATE DOANHSO CUA KHACHHANG TUONG UNG'
END

CREATE TRIGGER TRG_UPDATE_HOADON_DOANHSO ON HOADON
FOR UPDATE
AS
BEGIN
	DECLARE @MAKH_CU CHAR(4), @MAKH_MOI CHAR(4), @TRIGIA_CU MONEY, @TRIGIA_MOI MONEY

	SELECT @MAKH_CU = MAKH, @TRIGIA_CU = TRIGIA FROM  deleted
	SELECT @MAKH_MOI = MAKH, @TRIGIA_MOI = TRIGIA FROM  inserted
	
	IF(@MAKH_CU = @MAKH_MOI)
		BEGIN
			UPDATE KHACHHANG
			SET DOANHSO = DOANHSO + @TRIGIA_MOI - @TRIGIA_CU
			WHERE MAKH = @MAKH_CU
		END
	ELSE
		BEGIN
			UPDATE KHACHHANG
			SET DOANHSO = DOANHSO - @TRIGIA_CU
			WHERE MAKH = @MAKH_CU
			UPDATE KHACHHANG
			SET DOANHSO = DOANHSO + @TRIGIA_MOI
			WHERE MAKH = @MAKH_MOI
		END
	PRINT 'CAP NHAT THANH CONG TRIGIA HOADON VA UPDATE LAI DOANHSO KHACHHANG TUONG UNG'
END

CREATE TRIGGER TRG_DELETE_HOADON_DOANHSO ON HOADON
FOR DELETE
AS
BEGIN
	DECLARE @MAKH INT, @TRIGIA MONEY
	SELECT @MAKH = MAKH, @TRIGIA = TRIGIA FROM deleted

	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO - @TRIGIA
	WHERE MAKH = @MAKH

	PRINT 'XOA THANH CONG HOADON VA UPDATE LAI DOANHSO CUA KHACHHANG TUONG UNG'
END


--BAI TAP LAM THEM

USE QLGV

--I.9

CREATE TRIGGER TRG_INS_UPD_LOPTRUONG ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MALOP_LOP CHAR(3), @TRGLOP CHAR(5), @MALOP_HV CHAR(3)
	SELECT @MALOP_LOP = MALOP, @TRGLOP = TRGLOP FROM inserted
	SELECT @MALOP_HV = MALOP FROM HOCVIEN WHERE MAHV = @TRGLOP
	IF (@MALOP_LOP != @MALOP_HV)
		BEGIN
			PRINT 'LOI, LOP TRUONG PHAI LA HOC VIEN CUA LOP DO'
			ROLLBACK TRANSACTION
		END
END

CREATE TRIGGER TRG_DEL_LOPTRUONG ON HOCVIEN
FOR DELETE
AS
BEGIN
	DECLARE @MAHV CHAR(5), @MALOP CHAR(3), @TRGLOP CHAR(5)
	SELECT @MAHV = MAHV, @MALOP = MALOP FROM deleted
	SELECT @TRGLOP = TRGLOP FROM LOP WHERE MALOP = @MALOP
	IF (@MAHV = @TRGLOP)
	BEGIN
		PRINT 'KHONG THE XOA VI HOC VIEN DANG LA LOP TRUONG'
		ROLLBACK TRANSACTION
	END
END

--I.11
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_TUOI CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

--I.12
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_GIANGDAY CHECK (TUNGAY < DENNGAY)

--I.13
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_TUOILAM CHECK (YEAR(NGVL) - YEAR(NGSINH) >= 22)

--I.14
ALTER TABLE MONHOC ADD CONSTRAINT CHECK_TINCHI CHECK (ABS(TCLT - TCTH) <= 3)















